name: Build DEV docker image

on:
  push:
    branches:
      - 'develop'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.HUB_BASS_USERNAME }}
          password: ${{ secrets.HUB_BASS_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          target: dist
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            barassistant/server:dev
            ghcr.io/barassistant/server:dev
          build-args: BAR_ASSISTANT_VERSION=develop
          cache-from: type=gha
          cache-to: type=gha,mode=max
